spring.application.name=practica

# Fijar el nombre de la base de datos para facilitar el acceso en la consola
spring.datasource.url=jdbc:h2:mem:testdb


# Habilitar la consola web de H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
